// Shared WC 2026 match data — consumed by PredictionsTab and the daily
// tweet cron (/api/cron/post-wc-prediction). Keep this file pure TS
// (no React imports) so it can run in edge / Node cron contexts.

export type WCFactorType =
  | "host"          // Home-country advantage
  | "champion"      // Defending champion pressure/boost
  | "revenge"       // Historical/political rivalry
  | "derby"         // Continental derby
  | "cohesion"      // High squad club cohesion
  | "momentum"      // Outstanding qualifier form
  | "underdog"      // Surprise factor / underdog energy
  | "veterans"      // Experienced squad in final tournament
  | "pressure"      // Must-win psychological pressure

export const WC_FACTOR_META: Record<WCFactorType, { label: string; color: string; icon: string; desc: string }> = {
  host:      { label: "Avantage hôte",        color: "#00d4ff", icon: "🏟️", desc: "Soutien du public local · Acclimatation · Pression absente" },
  champion:  { label: "Tenant du titre",      color: "#fbbf24", icon: "🏆", desc: "Expérience de champions · Mais pression de confirmer" },
  revenge:   { label: "Revanche historique",  color: "#f97316", icon: "🔥", desc: "Contexte émotionnel fort · Motivation décuplée des deux côtés" },
  derby:     { label: "Derby continental",    color: "#a78bfa", icon: "⚡", desc: "Rivalité de voisinage · Matchs toujours serrés" },
  cohesion:  { label: "Cohésion de club",     color: "#22c55e", icon: "🤝", desc: "Joueurs évoluant ensemble en club · Automatismes rôdés" },
  momentum:  { label: "Élan qualificatif",    color: "#34d399", icon: "📈", desc: "Série impressionnante en éliminatoires · Confiance maximale" },
  underdog:  { label: "Effet surprise",       color: "#06b6d4", icon: "💥", desc: "L'équipe n'a rien à perdre · Jeu libéré et dangereux" },
  veterans:  { label: "Leadership vétérans",  color: "#94a3b8", icon: "🧠", desc: "Expérience décisive des matchs couperets · Gestion du stress" },
  pressure:  { label: "Pression enjeu",       color: "#ef4444", icon: "😤", desc: "Match décisif pour la qualification · Nerfs à vif" },
};

export interface WCMatch {
  group: string; date: string; venue: string;
  home: string; away: string;
  hP: number; dP: number; aP: number;
  winner: "home" | "away" | "draw";
  conf: "high" | "medium" | "low";
  note: string;
  // Rich details
  scorePredict: string;
  xgHome: number; xgAway: number;
  overUnder: "O2.5" | "U2.5" | "O1.5";
  btts: boolean;
  keyHome: string;
  keyAway: string;
  h2h: string;
  h2hDetail: string;
  wcFactor: WCFactorType;
  wcFactorTeam: "home" | "away" | "both";
  momentumHome: string;
  momentumAway: string;
  tacticHome: string;
  tacticAway: string;
  keyBattle: string;
  tacticalNote: string;
}

export const WC_MATCHES_DATA: WCMatch[] = [
  {
    group:"B", date:"11 juin", venue:"Mexico City – Azteca",
    home:"🇲🇽 Mexique", away:"🇪🇨 Équateur",
    hP:54, dP:24, aP:22, winner:"home", conf:"medium", note:"Match d'ouverture 🚀",
    scorePredict:"2-1", xgHome:1.9, xgAway:1.3,
    overUnder:"O2.5", btts:true,
    keyHome:"Hirving Lozano", keyAway:"Moisés Caicedo",
    h2h:"Mexique mène 6-3-4", h2hDetail:"13 confrontations · Mexique avantagé",
    wcFactor:"host", wcFactorTeam:"home",
    momentumHome:"7V 3N 0D", momentumAway:"6V 2N 2D",
    tacticHome:"4-3-3 Pressing haut",
    tacticAway:"4-4-2 Structuré",
    keyBattle:"Milieu central — Caicedo doit casser l'élan mexicain pour ouvrir les espaces en contre",
    tacticalNote:"Ambiance Azteca unique au monde · Mexique très difficile à battre chez lui en match d'ouverture · Lozano et l'ailier droit clés pour déborder le bloc équatorien",
  },
  {
    group:"C", date:"12 juin", venue:"Los Angeles – SoFi Stadium",
    home:"🇺🇸 USA", away:"🇵🇦 Panama",
    hP:64, dP:22, aP:14, winner:"home", conf:"high", note:"",
    scorePredict:"2-0", xgHome:2.1, xgAway:0.8,
    overUnder:"U2.5", btts:false,
    keyHome:"Christian Pulisic", keyAway:"Rolando Blackburn",
    h2h:"USA mène 11-4-3", h2hDetail:"18 confrontations · Domination US",
    wcFactor:"host", wcFactorTeam:"home",
    momentumHome:"8V 1N 1D", momentumAway:"5V 3N 2D",
    tacticHome:"4-3-3 Transition rapide",
    tacticAway:"5-4-1 Bloc défensif",
    keyBattle:"Pulisic entre les lignes — exploiter les espaces dans le 5-4-1 panaméen par des combinaisons courtes",
    tacticalNote:"Pulisic en forme record avec l'AC Milan · Panama qualifié de justesse après barrage · Défense US physique et organisée face à un attaquant limité",
  },
  {
    group:"A", date:"13 juin", venue:"Dallas – AT&T Stadium",
    home:"🇦🇷 Argentine", away:"🇨🇱 Chili",
    hP:65, dP:21, aP:14, winner:"home", conf:"high", note:"🏆 Tenant du titre",
    scorePredict:"2-0", xgHome:2.3, xgAway:0.9,
    overUnder:"O2.5", btts:false,
    keyHome:"Julián Álvarez", keyAway:"Alexis Sánchez",
    h2h:"Argentine mène 46-19-15", h2hDetail:"80 confrontations · Classique CONMEBOL",
    wcFactor:"champion", wcFactorTeam:"home",
    momentumHome:"7V 3N 0D", momentumAway:"4V 3N 3D",
    tacticHome:"4-3-3 Possession contrôlée",
    tacticAway:"4-4-2 Bloc médian",
    keyBattle:"Álvarez en pivot vs la défense centrale chilienne — Argentine cherchera à ouvrir sur les flancs",
    tacticalNote:"Messi incertain mais Álvarez et Lautaro suffisent · Chili en reconstruction post-génération dorée · Argentine joue en bloc et impose son tempo via De Paul au milieu",
  },
  {
    group:"E", date:"14 juin", venue:"Miami – Hard Rock Stadium",
    home:"🇪🇸 Espagne", away:"🇲🇦 Maroc",
    hP:54, dP:27, aP:19, winner:"home", conf:"medium", note:"⚠️ Piège potentiel",
    scorePredict:"1-1", xgHome:1.6, xgAway:1.2,
    overUnder:"U2.5", btts:true,
    keyHome:"Lamine Yamal", keyAway:"Achraf Hakimi",
    h2h:"Espagne mène 5-2-1", h2hDetail:"8 confrontations · Maroc surprenant en 2022",
    wcFactor:"underdog", wcFactorTeam:"away",
    momentumHome:"9V 1N 0D", momentumAway:"7V 2N 1D",
    tacticHome:"4-3-3 Tiki-taka / Possession",
    tacticAway:"5-3-2 Pressing haut + Contre",
    keyBattle:"Yamal dans les espaces vs Hakimi en montée — le flanc droit marocain sera le couloir le plus tendu",
    tacticalNote:"Maroc demi-finaliste 2022 · Hakimi très motivé face à l'Espagne · Match de référence du groupe · Espagne doit éviter le guet-apens d'un bloc marocain discipliné",
  },
  {
    group:"F", date:"14 juin", venue:"New York – MetLife Stadium",
    home:"🇫🇷 France", away:"🇸🇦 Arabie Saoudite",
    hP:74, dP:15, aP:11, winner:"home", conf:"high", note:"🇫🇷 Les Bleus",
    scorePredict:"3-0", xgHome:2.8, xgAway:0.6,
    overUnder:"O2.5", btts:false,
    keyHome:"Kylian Mbappé", keyAway:"Salem Al-Dawsari",
    h2h:"France mène 3-1-0", h2hDetail:"Peu de confrontations · France nettement supérieure",
    wcFactor:"momentum", wcFactorTeam:"home",
    momentumHome:"8V 2N 0D", momentumAway:"4V 2N 4D",
    tacticHome:"4-3-3 Transitions rapides",
    tacticAway:"5-4-1 Défense profonde",
    keyBattle:"Mbappé en face à face isolé vs la ligne défensive saoudienne — profondeur et appel à déclencher",
    tacticalNote:"Mbappé veut effacer la défaite 2022 · Arabie Saoudite avait battu l'Argentine en 2022 mais niveau moindre ici · France en confiance après qualifs parfaites, la puissance offensive ne laisse aucun doute",
  },
  {
    group:"D", date:"15 juin", venue:"Vancouver – BC Place",
    home:"🇨🇦 Canada", away:"🇭🇳 Honduras",
    hP:60, dP:24, aP:16, winner:"home", conf:"medium", note:"🏟️ Pays hôte",
    scorePredict:"2-0", xgHome:1.8, xgAway:0.7,
    overUnder:"U2.5", btts:false,
    keyHome:"Alphonso Davies", keyAway:"Alberth Elis",
    h2h:"Canada mène 6-4-5", h2hDetail:"15 confrontations · Légère avance Canada",
    wcFactor:"host", wcFactorTeam:"home",
    momentumHome:"6V 3N 1D", momentumAway:"4V 3N 3D",
    tacticHome:"4-2-3-1 Physique et rapide",
    tacticAway:"4-5-1 Repli défensif",
    keyBattle:"Davies côté gauche vs le couloir défensif hondurien — sa vitesse et son dribble sont l'arme principale",
    tacticalNote:"2e participation seulement au Canada · Davies en feu avec le Bayern · Honduras solide en CONCACAF mais physiquement dépassé à ce niveau mondial",
  },
  {
    group:"I", date:"15 juin", venue:"Boston – Gillette Stadium",
    home:"🏴󠁧󠁢󠁥󠁮󠁧󠁿 Angleterre", away:"🇸🇳 Sénégal",
    hP:57, dP:25, aP:18, winner:"home", conf:"medium", note:"",
    scorePredict:"2-1", xgHome:1.8, xgAway:1.1,
    overUnder:"O2.5", btts:true,
    keyHome:"Jude Bellingham", keyAway:"Sadio Mané",
    h2h:"Angleterre mène 5-2-2", h2hDetail:"9 confrontations · Sénégal montant",
    wcFactor:"veterans", wcFactorTeam:"home",
    momentumHome:"7V 2N 1D", momentumAway:"8V 1N 1D",
    tacticHome:"4-3-3 Contrôle du ballon",
    tacticAway:"4-3-3 Pressing + contre rapide",
    keyBattle:"Bellingham vs Mané — duel de stars qui dictera le rythme du match et le résultat",
    tacticalNote:"Sénégal champion d'Afrique 2022 · Mané vétéran mais toujours décisif sur le contre · Angleterre doit éviter le piège de la transition sénégalaise · Bellingham doit contrôler les espaces au milieu",
  },
  {
    group:"G", date:"16 juin", venue:"San Francisco – Levi's Stadium",
    home:"🇧🇷 Brésil", away:"🇨🇴 Colombie",
    hP:56, dP:24, aP:20, winner:"home", conf:"medium", note:"Derby CONMEBOL",
    scorePredict:"2-1", xgHome:1.9, xgAway:1.3,
    overUnder:"O2.5", btts:true,
    keyHome:"Vinicius Jr", keyAway:"James Rodríguez",
    h2h:"Brésil mène 31-10-11", h2hDetail:"52 confrontations · Classique Amérique du Sud",
    wcFactor:"derby", wcFactorTeam:"both",
    momentumHome:"6V 3N 1D", momentumAway:"8V 1N 1D",
    tacticHome:"4-2-3-1 Technique et expansif",
    tacticAway:"4-4-2 Compact en transition",
    keyBattle:"Vinicius Jr vs la défense droite colombienne — son élimination ou sa libération conditionnera tout le résultat",
    tacticalNote:"Colombie invaincue en 2024 CONMEBOL qualifying (record absolu) · Brésil en reconstruction mais talent intact · James Rodríguez chef d'orchestre clé mais Brésil plus profond · Derby avec pression maximale des deux côtés",
  },
  {
    group:"H", date:"16 juin", venue:"Philadelphia – Lincoln Financial",
    home:"🇩🇪 Allemagne", away:"🇳🇱 Pays-Bas",
    hP:40, dP:30, aP:30, winner:"draw", conf:"low", note:"⚡ Choc européen",
    scorePredict:"1-1", xgHome:1.4, xgAway:1.4,
    overUnder:"O2.5", btts:true,
    keyHome:"Florian Wirtz", keyAway:"Virgil van Dijk",
    h2h:"Allemagne mène 24-13-12", h2hDetail:"49 confrontations · Rivalité historique intense",
    wcFactor:"derby", wcFactorTeam:"both",
    momentumHome:"7V 2N 1D", momentumAway:"8V 1N 1D",
    tacticHome:"4-3-3 Gegenpress moderne",
    tacticAway:"4-2-3-1 Physique et aérien",
    keyBattle:"Wirtz entre les lignes vs la dureté de Gravenberch — le contrôle du milieu décide du vainqueur",
    tacticalNote:"Wirtz meilleur joueur Bundesliga · Pays-Bas portés par une génération talentueuse · Aucun favori clair · xG 1.4–1.4 parfaitement équilibré · Les deux équipes misent sur le pressing haut et les transitions",
  },
  {
    group:"J", date:"17 juin", venue:"Houston – NRG Stadium",
    home:"🇮🇹 Italie", away:"🇭🇷 Croatie",
    hP:46, dP:32, aP:22, winner:"home", conf:"low", note:"Revanche Euro 2021",
    scorePredict:"1-0", xgHome:1.3, xgAway:0.9,
    overUnder:"U2.5", btts:false,
    keyHome:"Federico Chiesa", keyAway:"Luka Modrić",
    h2h:"Italie mène 9-4-5", h2hDetail:"18 confrontations · Modrić grand facteur",
    wcFactor:"veterans", wcFactorTeam:"away",
    momentumHome:"5V 4N 1D", momentumAway:"5V 3N 2D",
    tacticHome:"3-5-2 Solide et discipliné",
    tacticAway:"4-3-3 Technique croatienne",
    keyBattle:"Modrić dans le cœur du jeu vs le double pivot italien — la Croatie passe par son capitaine",
    tacticalNote:"Modrić possiblement son dernier grand tournoi · Italie solide défensivement mais créativité offensive limitée · Chiesa le seul capable de faire la différence côté azzurri · Match serré attendu entre deux équipes prudentes",
  },
  {
    group:"F", date:"20 juin", venue:"New York – MetLife Stadium",
    home:"🇫🇷 France", away:"🇨🇭 Suisse",
    hP:67, dP:20, aP:13, winner:"home", conf:"high", note:"🇫🇷 Les Bleus MD2",
    scorePredict:"2-0", xgHome:2.2, xgAway:0.8,
    overUnder:"O2.5", btts:false,
    keyHome:"Antoine Griezmann", keyAway:"Granit Xhaka",
    h2h:"France mène 17-11-9", h2hDetail:"37 confrontations · Suisse avait éliminé la France en 2021",
    wcFactor:"revenge", wcFactorTeam:"home",
    momentumHome:"8V 2N 0D", momentumAway:"6V 2N 2D",
    tacticHome:"4-3-3 Domination et profondeur",
    tacticAway:"4-2-3-1 Organisation sous pression",
    keyBattle:"Griezmann dans l'axe vs Xhaka — l'intelligence tactique des deux numéros 10 décide du tempo",
    tacticalNote:"La Suisse a éliminé la France à l'Euro 2020 aux tirs au but · Revanche en jeu pour les Bleus · Xhaka leader mental et techniquement irréprochable · France supérieure sur papier mais match piège psychologiquement",
  },
  {
    group:"D", date:"20 juin", venue:"Kansas City – Arrowhead Stadium",
    home:"🇺🇾 Uruguay", away:"🇵🇹 Portugal",
    hP:28, dP:26, aP:46, winner:"away", conf:"medium", note:"",
    scorePredict:"1-2", xgHome:1.0, xgAway:1.8,
    overUnder:"O2.5", btts:true,
    keyHome:"Darwin Núñez", keyAway:"Cristiano Ronaldo",
    h2h:"Uruguay mène 4-2-5", h2hDetail:"11 confrontations · Portugal léger avantage récent",
    wcFactor:"veterans", wcFactorTeam:"away",
    momentumHome:"6V 2N 2D", momentumAway:"7V 2N 1D",
    tacticHome:"4-4-2 Rugueux et compact",
    tacticAway:"4-3-3 Technique et rapide",
    keyBattle:"Darwin Núñez isolé en pointe vs la défense centrale portugaise — s'il est muselé, l'Uruguay n'a pas d'autre plan",
    tacticalNote:"Ronaldo possiblement sa 5e et dernière CdM · Motivation extrême pour partir en beauté · Darwin Núñez seul atout offensif uruguayen · Portugal supérieur collectivement mais Uruguay très solide défensivement",
  },
  {
    group:"E", date:"21 juin", venue:"Los Angeles – SoFi Stadium",
    home:"🇧🇪 Belgique", away:"🇯🇵 Japon",
    hP:53, dP:25, aP:22, winner:"home", conf:"medium", note:"⚠️ Ne pas sous-estimer",
    scorePredict:"2-1", xgHome:1.7, xgAway:1.2,
    overUnder:"O2.5", btts:true,
    keyHome:"Kevin De Bruyne", keyAway:"Takefusa Kubo",
    h2h:"Belgique mène 3-1-1", h2hDetail:"5 confrontations · Japon montant",
    wcFactor:"underdog", wcFactorTeam:"away",
    momentumHome:"5V 3N 2D", momentumAway:"8V 1N 1D",
    tacticHome:"4-3-3 Expérimenté mais vieillissant",
    tacticAway:"4-2-3-1 Pressing intense",
    keyBattle:"Kubo dans les espaces laissés par la défense belge vieillissante — le Japon joue sur la profondeur et les transitions rapides",
    tacticalNote:"Japon invaincue sur 10 matchs qualificatifs · Kubo explosif et en plein forme · De Bruyne décisif mais Belgique en fin de cycle générationnel · Match potentiellement piège pour une Belgique moins rapide",
  },
  {
    group:"A", date:"22 juin", venue:"Seattle – Lumen Field",
    home:"🇦🇷 Argentine", away:"🇦🇺 Australie",
    hP:76, dP:14, aP:10, winner:"home", conf:"high", note:"",
    scorePredict:"3-0", xgHome:2.9, xgAway:0.6,
    overUnder:"O2.5", btts:false,
    keyHome:"Lionel Messi", keyAway:"Mat Ryan",
    h2h:"Argentine mène 4-1-0", h2hDetail:"5 confrontations · Argentine très largement",
    wcFactor:"champion", wcFactorTeam:"home",
    momentumHome:"7V 3N 0D", momentumAway:"5V 2N 3D",
    tacticHome:"4-3-3 Domination absolue",
    tacticAway:"5-4-1 Survie et contre",
    keyBattle:"Messi en 10 vs le bloc défensif australien — toute la menace argentine passe par le capitaine",
    tacticalNote:"Argentine très largement dominatrice dans les statistiques · Australie en mode survie · Messi décisif à chaque grande affiche · Match qui doit confirmer le statut de champion du monde de l'Argentine",
  },
  {
    group:"F", date:"25 juin", venue:"New York – MetLife Stadium",
    home:"🇫🇷 France", away:"🇩🇿 Algérie",
    hP:56, dP:24, aP:20, winner:"home", conf:"medium", note:"🔥 Choc Historique",
    scorePredict:"2-1", xgHome:2.0, xgAway:1.4,
    overUnder:"O2.5", btts:true,
    keyHome:"Kylian Mbappé", keyAway:"Riyad Mahrez",
    h2h:"Jamais rencontré en CdM", h2hDetail:"1ère confrontation officielle en CdM · Amicaux: France 2-0",
    wcFactor:"revenge", wcFactorTeam:"away",
    momentumHome:"8V 2N 0D", momentumAway:"7V 2N 1D",
    tacticHome:"4-3-3 Pression et possession",
    tacticAway:"4-4-2 Bloc compact + contre",
    keyBattle:"Mbappé vs Mandi/Benlamri — la défense algérienne sera testée dès les premières minutes par la vitesse française",
    tacticalNote:"Match politique et émotionnel hors du commun · Nombreux joueurs franco-algériens dans les deux équipes · Mahrez et Benrahma sous pression identitaire · France favorite mais pression psychologique atypique",
  },
  {
    group:"G", date:"26 juin", venue:"San Francisco – Levi's Stadium",
    home:"🇧🇷 Brésil", away:"🇵🇾 Paraguay",
    hP:69, dP:20, aP:11, winner:"home", conf:"high", note:"",
    scorePredict:"2-0", xgHome:2.4, xgAway:0.7,
    overUnder:"O2.5", btts:false,
    keyHome:"Rodrygo", keyAway:"Miguel Almirón",
    h2h:"Brésil mène 38-14-15", h2hDetail:"67 confrontations · Domination brésilienne",
    wcFactor:"cohesion", wcFactorTeam:"home",
    momentumHome:"6V 3N 1D", momentumAway:"5V 3N 2D",
    tacticHome:"4-2-3-1 Contrôle et technique",
    tacticAway:"4-5-1 Défensif et physique",
    keyBattle:"Rodrygo dans le dos de la défense paraguayenne — sa capacité à dribbler dans l'espace est l'arme principale",
    tacticalNote:"Brésil avec 6 joueurs du Real Madrid et FC Barcelone — automatismes de haut niveau · Paraguay résistant en qualifs mais techniquement limité au plus haut niveau · Bloc paraguayen difficile à ouvrir mais manque de ressources offensives",
  },
  {
    group:"H", date:"26 juin", venue:"Seattle – Lumen Field",
    home:"🇩🇪 Allemagne", away:"🇵🇱 Pologne",
    hP:62, dP:22, aP:16, winner:"home", conf:"high", note:"",
    scorePredict:"2-0", xgHome:2.1, xgAway:0.9,
    overUnder:"O2.5", btts:false,
    keyHome:"Florian Wirtz", keyAway:"Robert Lewandowski",
    h2h:"Allemagne mène 34-9-4", h2hDetail:"47 confrontations · Domination historique allemande",
    wcFactor:"derby", wcFactorTeam:"home",
    momentumHome:"7V 2N 1D", momentumAway:"5V 3N 2D",
    tacticHome:"4-3-3 Haute intensité",
    tacticAway:"4-4-2 Solide et direct",
    keyBattle:"Lewandowski sur coups de pied arrêtés vs Rüdiger — le capitaine polonais reste une menace constante malgré les années",
    tacticalNote:"Lewandowski à 38 ans mais toujours redoutable sur coups de pied arrêtés · Allemagne doit sécuriser la 1re place du groupe · Wirtz et Havertz en charge de la créativité · Pologne tentera de défendre profondément et de frapper sur transition",
  },
  {
    group:"I", date:"27 juin", venue:"Boston – Gillette Stadium",
    home:"🏴󠁧󠁢󠁥󠁮󠁧󠁿 Angleterre", away:"🇹🇳 Tunisie",
    hP:70, dP:19, aP:11, winner:"home", conf:"high", note:"",
    scorePredict:"2-0", xgHome:2.3, xgAway:0.7,
    overUnder:"O2.5", btts:false,
    keyHome:"Bukayo Saka", keyAway:"Wahbi Khazri",
    h2h:"Angleterre mène 3-1-0", h2hDetail:"4 confrontations · Angleterre favorable",
    wcFactor:"pressure", wcFactorTeam:"both",
    momentumHome:"7V 2N 1D", momentumAway:"5V 2N 3D",
    tacticHome:"4-2-3-1 Contrôle et profondeur",
    tacticAway:"5-4-1 Bloc défensif",
    keyBattle:"Saka côté droit vs le mur tunisien — sa technique en 1v1 doit faire la différence pour créer des décalages",
    tacticalNote:"Angleterre a besoin d'une victoire convaincante pour assurer la qualification · Tunisie en CdM pour la 6e fois — expérience mais niveau insuffisant · Saka et Foden les créateurs offensifs clés · Match sans surprise tactique attendue mais Angleterre sous pression de bien performer",
  },
];
